services:
  postgres:
    container_name: postgres
    build: .
    environment:
      - POSTGRES_DB=piscineds
      - POSTGRES_USER=dcaetano
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

volumes:
  postgres_data:
    name: postgres_data
